import type { ArticleReglement } from "./types";

const SOURCE_CORSIER =
  "Règlement communal sur le plan d’extension et la police des constructions – Commune de Corsier-sur-Vevey";

export const REGLEMENT_CORSIER: ArticleReglement[] = [
  // CHAPITRE I – Dispositions générales
  {
    id: "corsier_gen_art1_but_reglement",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE I – Dispositions générales",
    article: "Art. 1",
    titreCourt: "But du règlement",
    texte:
      "Le présent règlement fixe, conformément à la loi vaudoise sur les constructions et l'aménagement du territoire, les règles destinées à assurer un aménagement rationnel du territoire de la commune de Corsier-sur-Vevey et un développement harmonieux des constructions.",
    motsCles: [
      "but du règlement",
      "aménagement du territoire",
      "développement harmonieux",
      "dispositions générales",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_gen_art2_complements",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE I – Dispositions générales",
    article: "Art. 2",
    titreCourt: "Compléments du règlement",
    texte:
      "La Municipalité établit : a) un plan directeur d'extension et, au fur et à mesure des besoins ; b) des plans partiels d’extension ; c) des plans de quartier.",
    motsCles: [
      "plan directeur d’extension",
      "plans partiels d’extension",
      "plans de quartier",
      "municipalité",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_gen_art3_commission_consultative",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE I – Dispositions générales",
    article: "Art. 3",
    titreCourt: "Commission consultative",
    texte:
      "Pour l'examen des objets relatifs au plan d'extension et à la police des constructions, la Municipalité peut prendre l'avis de personnes spécialisées en matière de construction et d'urbanisme.",
    motsCles: [
      "commission consultative",
      "avis spécialisé",
      "urbanisme",
      "police des constructions",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE II – Plan des zones
  {
    id: "corsier_zones_art4_definitions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE II – Plan des zones",
    article: "Art. 4",
    titreCourt: "Définition des zones",
    texte:
      "Le territoire de la commune de Corsier-sur-Vevey est divisé en 12 zones dont les périmètres respectifs sont déterminés par le plan annexé au présent règlement. L'inventaire des zones est le suivant : 1. Zone du village (teinte brune) ; 2. Zone d'habitation à forte densité (teinte rouge) ; 3. Zone d'habitation à moyenne densité (teinte orange) ; 4. Zone d'habitation à faible densité A (teinte jaune hachuré) ; 5. Zone d'habitation à faible densité B (teinte jaune) ; 6. Zone industrielle (teinte violet foncé) ; 7. Zone artisanale (teinte violet clair) ; 8. Zone de construction d'utilité publique (teinte bleue) ; 9. Zone intermédiaire (hachuré sans teinte) ; 10. Zone agricole (sans teinte) ; 11. Zone viticole (teinte grise) ; 12. Zone de verdure (teinte vert clair).",
    motsCles: [
      "plan des zones",
      "zone du village",
      "zone d’habitation",
      "zone industrielle",
      "zone agricole",
      "zone viticole",
      "zone de verdure",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_zones_art5_plans_speciaux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE II – Plan des zones",
    article: "Art. 5",
    titreCourt: "Plans spéciaux",
    texte:
      "Certaines zones comprennent des secteurs hachurés sur le plan des zones soumis à un plan de quartier ou à un plan partiel d’extension selon les dispositions de la LCAT.",
    motsCles: [
      "plans spéciaux",
      "plan de quartier",
      "plan partiel d’extension",
      "secteurs hachurés",
      "LCAT",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE III – Zone du village
  {
    id: "corsier_village_art6_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE III – Zone du village",
    article: "Art. 6",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone est destinée à l'habitation, au commerce et à l'artisanat, pour autant que ceux-ci soient compatibles avec l'habitation, ainsi qu'aux équipements collectifs.",
    motsCles: [
      "zone du village",
      "habitation",
      "commerce",
      "artisanat",
      "équipements collectifs",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_village_art7_batiments_existants",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE III – Zone du village",
    article: "Art. 7",
    titreCourt: "Bâtiments existants",
    texte:
      "Les bâtiments existants peuvent être entretenus, transformés ou reconstruits dans leurs implantation et gabarit actuels, sous réserve de légères modifications admises par la Municipalité. Les volumes existants peuvent être utilisés sans limitation. La Municipalité peut notamment autoriser des agrandissements de peu d'importance (lucarnes, dômes, légère surélévation de la toiture, etc.). Tous les travaux prévus ci-dessus ne peuvent être autorisés que s'il n'en résulte pas d'atteinte au caractère de l'ensemble architectural. Les plans d'alignement des constructions sont réservés.",
    motsCles: [
      "bâtiments existants",
      "entretien",
      "transformation",
      "reconstruction",
      "gabarit",
      "agrandissements",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_village_art8_nouvelles_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE III – Zone du village",
    article: "Art. 8",
    titreCourt: "Nouvelles constructions",
    texte:
      "Toutes les constructions autres que celles prévues à l'article 7 ne peuvent être autorisées que moyennant l'approbation préalable d'un plan de quartier ou d'un plan partiel d'extension.",
    motsCles: [
      "nouvelles constructions",
      "plan de quartier",
      "plan partiel d’extension",
      "zone du village",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_village_art9_esthetique",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE III – Zone du village",
    article: "Art. 9",
    titreCourt: "Esthétique",
    texte:
      "Par leur forme, leur volume, l'architecture de leurs façades (rythme, forme des percements et couleur des façades), leur toiture, les constructions doivent s'intégrer à l'ensemble de façon à former un tout homogène.",
    motsCles: [
      "esthétique",
      "intégration",
      "façades",
      "toiture",
      "caractère homogène",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_village_art10_plans_elevation",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE III – Zone du village",
    article: "Art. 10",
    titreCourt: "Plans d’enquête et élévations",
    texte:
      "Sur les plans d'enquête, les bâtiments voisins de celui projeté ou pour lequel une modification est prévue seront dessinés en élévation, de façon à rendre intelligible l'intégration de la nouvelle construction dans le site.",
    motsCles: [
      "plans d’enquête",
      "bâtiments voisins",
      "élévation",
      "intégration dans le site",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE IV – Zone d'habitation à forte densité
  {
    id: "corsier_hfd_art11_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 11",
    titreCourt: "Définition de la zone",
    texte: "Cette zone est destinée à l'habitation collective.",
    motsCles: [
      "zone d’habitation à forte densité",
      "habitation collective",
      "immeubles",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art12_ordre_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 12",
    titreCourt: "Ordre des constructions",
    texte: "L'ordre non contigu est obligatoire.",
    motsCles: ["ordre non contigu", "implantation", "bâtiments"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art13_surface_constructible",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 13",
    titreCourt: "Surface constructible",
    texte:
      "La surface bâtie ne peut excéder le 1/6 de la surface totale de la parcelle.",
    motsCles: [
      "surface bâtie",
      "surface totale",
      "1/6",
      "densité",
      "constructibilité",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art14_nombre_niveaux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 14",
    titreCourt: "Nombre de niveaux",
    texte:
      "Le nombre de niveaux habitables est limité à quatre sous la corniche sans combles habitables ou trois sous la corniche plus un dans les combles. Dans les terrains en pente, la Municipalité peut autoriser des locaux habitables en dessous du rez-de-chaussée, mais sur un seul niveau. La surface de ces locaux ne peut dépasser la moitié de la surface du niveau immédiatement supérieur. Dans ce cas, la hauteur maximum de la façade aval mesurée sur la corniche est augmentée de 2,50 m.",
    motsCles: [
      "nombre de niveaux",
      "combles",
      "terrains en pente",
      "façade aval",
      "2,50 m",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art15_hauteur_facades",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 15",
    titreCourt: "Hauteur des façades",
    texte:
      "La hauteur des façades mesurée sur la corniche ne dépassera pas 16 mètres (voir art. 68). Dans le secteur quadrillé, la hauteur des bâtiments telle qu'existante à l'entrée en vigueur du présent règlement ne peut être augmentée.",
    motsCles: [
      "hauteur des façades",
      "16 mètres",
      "secteur quadrillé",
      "art. 68",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art16_distances",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 16",
    titreCourt: "Distances entre façades et limites",
    texte:
      "La distance minimum entre chaque façade et la limite de propriété voisine est de 6 mètres pour les bâtiments jusqu'à 24 mètres. Pour les bâtiments dont la plus grande dimension est supérieure à 24 mètres, elle est augmentée de 15 centimètres par mètre supplémentaire. Entre bâtiments sis sur une même propriété, ces distances sont additionnées.",
    motsCles: [
      "distance aux limites",
      "6 mètres",
      "24 mètres",
      "15 centimètres par mètre",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art17_toiture",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 17",
    titreCourt: "Toiture",
    texte:
      "Les toits plats peuvent être autorisés pour autant qu'ils soient compatibles avec les constructions avoisinantes et le caractère des lieux.",
    motsCles: ["toits plats", "compatibilité", "caractère des lieux"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfd_art18_places_jeux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IV – Zone d'habitation à forte densité",
    article: "Art. 18",
    titreCourt: "Places de jeux",
    texte:
      "Des places de jeux pour enfants d'une surface minimum de 10 m² par 100 m² de surface habitable sont aménagées par les propriétaires, qui en assurent l'entretien.",
    motsCles: ["places de jeux", "enfants", "surface habitable"],
    typeSource: "RGA",
  },

  // CHAPITRE V – Zone d'habitation à moyenne densité
  {
    id: "corsier_hmd_art19_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE V – Zone d'habitation à moyenne densité",
    article: "Art. 19",
    titreCourt: "Définition de la zone",
    texte: "Cette zone est destinée à l’habitation collective.",
    motsCles: [
      "zone d’habitation à moyenne densité",
      "habitation collective",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hmd_art20_nombre_niveaux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE V – Zone d'habitation à moyenne densité",
    article: "Art. 20",
    titreCourt: "Nombre de niveaux",
    texte:
      "Le nombre de niveaux habitables est limité à quatre sous la corniche sans combles habitables ou trois sous la corniche plus un dans les combles.",
    motsCles: ["nombre de niveaux", "combles", "habitation collective"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hmd_art21_hauteur_facades",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE V – Zone d'habitation à moyenne densité",
    article: "Art. 21",
    titreCourt: "Hauteur des façades",
    texte:
      "La hauteur des façades mesurée sur la corniche ne dépassera pas 13 mètres (voir art. 68).",
    motsCles: ["hauteur des façades", "13 mètres", "art. 68"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hmd_art22_autres_regles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE V – Zone d'habitation à moyenne densité",
    article: "Art. 22",
    titreCourt: "Autres règles",
    texte:
      "Les articles 12, 13, 14, 15, 16, 17 et 18 de la zone d'habitation à forte densité sont applicables.",
    motsCles: [
      "référence",
      "zone à forte densité",
      "articles 12 à 18",
      "application",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE VI – Zone d'habitation à faible densité A
  {
    id: "corsier_hfa_art23_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 23",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone est destinée aux maisons, villas, petits bâtiments d'habitation comptant au plus quatre appartements. Les habitations genre chalet ne sont pas admises.",
    motsCles: [
      "faible densité A",
      "maisons",
      "villas",
      "chalets non admis",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfa_art24_ordre_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 24",
    titreCourt: "Ordre des constructions",
    texte: "L'ordre non contigu est obligatoire.",
    motsCles: ["ordre non contigu", "implantation"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfa_art25_distance_limites",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 25",
    titreCourt: "Distance aux limites",
    texte:
      "La distance entre un bâtiment et la limite de la propriété voisine est au minimum de 5 mètres. Entre bâtiments sis sur une même propriété, ces distances sont additionnées.",
    motsCles: ["distance aux limites", "5 mètres"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfa_art26_surface_min_parcelles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 26",
    titreCourt: "Surface minimum des parcelles",
    texte:
      "Toute construction de bâtiments d'habitation est interdite sur des parcelles n'ayant pas une surface de 800 m² au minimum, à raison d'une maison d'habitation par 800 m².",
    motsCles: ["surface minimale", "800 m²", "parcelles"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfa_art27_surface_constructible",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 27",
    titreCourt: "Surface constructible",
    texte:
      "La surface bâtie ne peut excéder le 1/6 de la surface totale de la parcelle.",
    motsCles: ["surface bâtie", "1/6", "surface totale"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfa_art28_surface_min_batiments",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 28",
    titreCourt: "Surface minimum des bâtiments",
    texte:
      "Les bâtiments d'habitation auront au minimum une surface de 70 m².",
    motsCles: ["surface minimale", "bâtiments", "70 m²"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfa_art29_hauteur_niveaux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VI – Zone d'habitation à faible densité A",
    article: "Art. 29",
    titreCourt: "Hauteur et nombre de niveaux",
    texte:
      "Les bâtiments de moins de 90 m² de surface comptent au maximum un rez-de-chaussée et des combles habitables sur un niveau. La hauteur sur la corniche est limitée à 4 mètres au maximum. Pour les bâtiments de plus de 90 m², le nombre de niveaux habitables est limité à un rez-de-chaussée et un étage sous la corniche ou un rez-de-chaussée et des combles habitables sur un niveau. La hauteur à la corniche ne peut dépasser 6,50 m (voir art. 68). Dans les terrains en pente, la Municipalité peut autoriser des locaux habitables en dessous du rez-de-chaussée mais sur un seul niveau. La surface de ces locaux ne peut dépasser une fraction de la surface du niveau immédiatement supérieur. Dans ce cas, la hauteur maximum de la façade aval mesurée sur la corniche est augmentée de 2,50 m.",
    motsCles: [
      "hauteur",
      "nombre de niveaux",
      "90 m²",
      "4 m",
      "6,50 m",
      "terrains en pente",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE VII – Zone d’habitation à faible densité B
  {
    id: "corsier_hfb_art30_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 30",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone est destinée aux maisons familiales et chalets, ceux-ci comptant au plus deux appartements. Dans le secteur « Le Mur Blanc », seules sont autorisées les constructions de type chalet.",
    motsCles: ["faible densité B", "maisons familiales", "chalets", "Mur Blanc"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfb_art31_ordre_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 31",
    titreCourt: "Ordre des constructions",
    texte: "L'ordre non contigu est obligatoire.",
    motsCles: ["ordre non contigu"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfb_art32_distance_limites",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 32",
    titreCourt: "Distances aux limites",
    texte:
      "La distance entre un bâtiment et la limite de la propriété voisine est au minimum de 6 mètres. Entre les bâtiments sis sur une même propriété, ces distances sont additionnées.",
    motsCles: ["distance aux limites", "6 mètres"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfb_art33_surface_min_parcelles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 33",
    titreCourt: "Surface minimum des parcelles",
    texte:
      "Toute construction de bâtiment d'habitation est interdite sur des parcelles n'ayant pas une surface de 1000 m² au minimum, à raison d'une maison familiale ou d'un chalet par 1000 m².",
    motsCles: ["surface minimale", "1000 m²", "parcelles"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfb_art34_surface_constructible",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 34",
    titreCourt: "Surface constructible",
    texte:
      "La surface bâtie ne peut excéder le 1/8 de la surface totale de la parcelle.",
    motsCles: ["surface bâtie", "1/8", "surface totale"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfb_art35_surface_min_batiments",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 35",
    titreCourt: "Surface minimum des bâtiments",
    texte:
      "Les bâtiments d'habitation auront au minimum une surface de 45 m².",
    motsCles: ["surface minimale", "45 m²"],
    typeSource: "RGA",
  },
  {
    id: "corsier_hfb_art36_hauteur_niveaux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VII – Zone d’habitation à faible densité B",
    article: "Art. 36",
    titreCourt: "Hauteur et nombre de niveaux",
    texte: "L’article 29 est applicable.",
    motsCles: ["hauteur", "nombre de niveaux", "référence art. 29"],
    typeSource: "RGA",
  },

  // CHAPITRE VIII – Zone industrielle
  {
    id: "corsier_indus_art37_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 37",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone est réservée aux établissements industriels, fabriques, entrepôts, garages-ateliers ainsi qu’aux entreprises artisanales qui entraîneraient dans d'autres zones des inconvénients pour le voisinage. L'habitation de modeste importance peut être admise si elle est nécessitée par une obligation de gardiennage ou d'autres raisons jugées valables par la Municipalité.",
    motsCles: [
      "zone industrielle",
      "établissements industriels",
      "entrepôts",
      "garages-ateliers",
      "habitation de gardiennage",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_indus_art38_restrictions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 38",
    titreCourt: "Restriction d’activités",
    texte:
      "Toute activité susceptible d’entraîner une gêne sensible pour les zones avoisinantes est interdite.",
    motsCles: [
      "gêne sensible",
      "zones avoisinantes",
      "nuisances",
      "restriction",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_indus_art39_ordre_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 39",
    titreCourt: "Ordre des constructions",
    texte: "L'ordre non contigu est obligatoire.",
    motsCles: ["ordre non contigu"],
    typeSource: "RGA",
  },
  {
    id: "corsier_indus_art40_distance_limites",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 40",
    titreCourt: "Distances aux limites",
    texte:
      "La distance minimum « d » entre la façade d'un bâtiment industriel et la limite de propriété voisine est fonction de la hauteur moyenne « h » de cette façade, mesurée dès la cote moyenne du terrain naturel au droit de celle-ci : si « h » est inférieure à 6 mètres : « d » = 6 mètres ; si « h » est supérieure à 6 mètres : « d » = « h ».",
    motsCles: ["distance aux limites", "bâtiment industriel", "h", "d", "6 m"],
    typeSource: "RGA",
  },
  {
    id: "corsier_indus_art41_volume_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 41",
    titreCourt: "Volumes des constructions",
    texte:
      "Le volume maximum des constructions au-dessus du sol naturel ne dépassera pas 4 mètres cubes par mètre carré de la surface totale de la parcelle.",
    motsCles: ["volume maximum", "4 m³/m²", "surface totale"],
    typeSource: "RGA",
  },
  {
    id: "corsier_indus_art42_places_stationnement",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 42",
    titreCourt: "Places de stationnement",
    texte:
      "Des places de stationnement pour véhicules doivent être prévues en suffisance, la Municipalité pouvant se référer aux normes de l'Union suisse des professionnels de la route.",
    motsCles: ["places de stationnement", "véhicules", "USPR"],
    typeSource: "RGA",
  },
  {
    id: "corsier_indus_art43_arborisation",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE VIII – Zone industrielle",
    article: "Art. 43",
    titreCourt: "Arborisation",
    texte:
      "La Municipalité peut imposer la plantation d'arbres, de rideaux d'arbres, de haies, en particulier le long des voies publiques et des limites de propriété. Elle peut fixer les essences à utiliser.",
    motsCles: ["arborisation", "plantations", "haies", "voies publiques"],
    typeSource: "RGA",
  },

  // CHAPITRE IX – Zone artisanale
  {
    id: "corsier_artis_art44_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IX – Zone artisanale",
    article: "Art. 44",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone est réservée aux entreprises artisanales et aux petites industries. L'habitation en relation directe avec l'exploitation est autorisée.",
    motsCles: ["zone artisanale", "petites industries", "habitation liée"],
    typeSource: "RGA",
  },
  {
    id: "corsier_artis_art45_surface_max_batiments",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IX – Zone artisanale",
    article: "Art. 45",
    titreCourt: "Surface maximum des bâtiments",
    texte:
      "La surface d'occupation du sol est au maximum de 800 m² par construction.",
    motsCles: ["surface d’occupation du sol", "800 m²"],
    typeSource: "RGA",
  },
  {
    id: "corsier_artis_art46_autres_regles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE IX – Zone artisanale",
    article: "Art. 46",
    titreCourt: "Autres règles",
    texte:
      "Les articles 38 à 43 du chapitre VIII de la zone industrielle sont applicables.",
    motsCles: ["référence", "zone industrielle", "articles 38 à 43"],
    typeSource: "RGA",
  },

  // CHAPITRE X – Zone de constructions d'utilité publique
  {
    id: "corsier_utilpub_art47_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE X – Zone de constructions d'utilité publique",
    article: "Art. 47",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone est destinée exclusivement à l'édification de constructions d'intérêt public et à l'aménagement de places de jeux et de sports. La distance entre un bâtiment et la limite de la propriété voisine ainsi que les autres conditions de construction (hauteur, volume, etc.) sont fixées de cas en cas par la Municipalité en fonction de l'intérêt public et en tenant compte de l'intérêt des voisins.",
    motsCles: [
      "utilité publique",
      "constructions d’intérêt public",
      "places de jeux",
      "places de sports",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE XI – Zone intermédiaire
  {
    id: "corsier_inter_art48_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XI – Zone intermédiaire",
    article: "Art. 48",
    titreCourt: "Définition de la zone",
    texte:
      "Cette zone s'étend aux terrains dont l'affectation sera définie ultérieurement. En tant que telle, cette zone est inconstructible ; cependant, des plans partiels d'extension ou des plans de quartier peuvent y être établis, dans les limites fixées par l'article 25 ter, premier alinéa, LCAT. L’article 59 est applicable aux bâtiments existants.",
    motsCles: ["zone intermédiaire", "inconstructible", "plans spéciaux", "LCAT"],
    typeSource: "RGA",
  },

  // CHAPITRE XII – Zone agricole
  {
    id: "corsier_agri_art49_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XII – Zone agricole",
    article: "Art. 49",
    titreCourt: "Définition de la zone",
    texte:
      "La zone agricole est destinée aux activités en relation avec la culture du sol et l'élevage.",
    motsCles: ["zone agricole", "culture du sol", "élevage"],
    typeSource: "RGA",
  },
  {
    id: "corsier_agri_art50_constructions_autorisees",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XII – Zone agricole",
    article: "Art. 50",
    titreCourt: "Nouvelles constructions",
    texte:
      "Les constructions et installations autorisées dans la zone agricole sont les suivantes : a) les bâtiments nécessaires à l'exploitation d'un domaine agricole favorisant le but assigné à la zone agricole ; l’habitation pour l'exploitant et le personnel des exploitations ci-dessus mentionnées, pour autant que ces bâtiments forment un ensemble architectural avec les bâtiments d'exploitation. b) La Municipalité peut, en outre, autoriser en zone agricole les constructions suivantes, à condition que leur implantation soit imposée par leur destination et n'entrave pas les exploitations agricoles existantes : constructions et installations nécessaires à une des exploitations assimilées à l'agriculture (établissements d'élevage, horticoles, arboricoles, maraîchers, etc.), bâtiments d'habitation pour l'exploitant et le personnel de ces entreprises, bâtiments et installations de minime importance liés aux loisirs et à la détente en plein air, sans habitation permanente, ainsi que les constructions et installations d'intérêt public ou indispensables à un service public, et les aménagements sportifs d'intérêt communal. La commune n’a pas l'obligation d'entreprendre dans cette zone une extension de la voirie, des réseaux d'égouts et d'eau potable qui pourraient exister.",
    motsCles: [
      "constructions agricoles",
      "exploitations assimilées",
      "intérêt public",
      "loisirs",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_agri_art51_distance_limites",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XII – Zone agricole",
    article: "Art. 51",
    titreCourt: "Distance aux limites",
    texte:
      "La distance à la limite de propriété ne peut être inférieure à 6 mètres.",
    motsCles: ["distance aux limites", "6 mètres"],
    typeSource: "RGA",
  },

  // CHAPITRE XIII – Zone viticole
  {
    id: "corsier_viticole_art52_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XIII – Zone viticole",
    article: "Art. 52",
    titreCourt: "Définition de la zone",
    texte:
      "La zone viticole est destinée à la culture de la vigne. Sous réserve de l'article 53, elle est inconstructible.",
    motsCles: ["zone viticole", "vigne", "inconstructible"],
    typeSource: "RGA",
  },
  {
    id: "corsier_viticole_art53_constructions_nouvelles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XIII – Zone viticole",
    article: "Art. 53",
    titreCourt: "Construction nouvelle",
    texte:
      "Les ouvrages, aménagements et installations en relation directe avec l'exploitation de la vigne sont autorisés, ainsi que les petits bâtiments à usage professionnel directement liés à la viticulture et complémentaires du centre d'exploitation principal.",
    motsCles: [
      "ouvrages viticoles",
      "installations viticoles",
      "usage professionnel",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE XIV – Zone de verdure
  {
    id: "corsier_verdure_art54_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XIV – Zone de verdure",
    article: "Art. 54",
    titreCourt: "Zone de verdure",
    texte:
      "Cette zone est destinée à la protection des sites et à la création ou conservation d’îlots de verdure. Elle est caractérisée par l'interdiction de bâtir.",
    motsCles: ["zone de verdure", "protection des sites", "interdiction de bâtir"],
    typeSource: "RGA",
  },

  // CHAPITRE XV – Règles générales applicables à toutes les zones
  {
    id: "corsier_regles_art55_esthetique_generale",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 55",
    titreCourt: "Esthétique générale",
    texte:
      "La Municipalité peut prendre toutes les mesures utiles pour éviter l'enlaidissement du territoire communal. Sauf dans la zone industrielle, les entrepôts et dépôts ouverts à la vue du public sont interdits. La Municipalité peut exiger des plantations pour masquer les installations existantes et en fixer les essences. Les constructions, agrandissements, transformations, crépis, peintures, affiches, etc., de nature à nuire au bon aspect d'un lieu sont interdits. Les installations non soumises à autorisation doivent avoir un aspect satisfaisant. Toutes les façades qui ne sont ni mitoyennes, ni adjacentes doivent être ajourées ou traitées de façon à ne pas nuire à l’esthétique.",
    motsCles: ["esthétique", "enlaidissement", "entrepôts", "plantations"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art56_protection_architecturale",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 56",
    titreCourt: "Protection architecturale",
    texte:
      "La Municipalité prend toutes les dispositions nécessaires pour maintenir et préserver le patrimoine architectural, en particulier pour les bâtiments ou autres constructions présentant un intérêt architectural digne de protection.",
    motsCles: ["protection architecturale", "patrimoine", "bâtiments dignes de protection"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art57_integration_constructions",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 57",
    titreCourt: "Intégration des constructions",
    texte:
      "La Municipalité veille particulièrement à ce que les nouvelles constructions aient un aspect architectural s’intégrant au site.",
    motsCles: ["intégration", "aspect architectural", "site"],
    typeSource: "RGA",
  },

  {
    id: "corsier_regles_art58_batiments_existants_zones_batir",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 58",
    titreCourt:
      "Bâtiments existants non réglementaires a) dans les zones à bâtir",
    texte:
      "Les bâtiments existants et qui ne sont pas conformes au présent règlement sont soumis aux dispositions de l'art. 28 de la loi sur les constructions et l'aménagement du territoire du 5 février 1941 et de l'art. 24 de la loi sur le plan de protection de Lavaux du 12 février 1979, dans le périmètre dudit plan. Cependant, et en application de l'art. 28, alinéa premier, dernière phrase, de la LCAT, la Municipalité peut autoriser des agrandissements mineurs du gabarit de ces bâtiments, ainsi que la construction de petites dépendances, pour autant que leur intégration soit satisfaisante et sous réserve d'une éventuelle mention de précarité. Elle peut également autoriser une rénovation ou un changement d'affectation pour autant qu'il n'en résulte pas une atteinte importante à la destination, au caractère ou au développement de la zone. Une reconstruction pourra également être autorisée aux mêmes conditions et dans un volume équivalent en cas de destruction accidentelle. Un éventuel agrandissement ne doit pas avoir pour effet d’aggraver le caractère non réglementaire de la construction en ce qui concerne notamment la hauteur, les distances aux limites, le coefficient d'occupation ou d'utilisation du sol, sauf dans les cas exceptionnels où il peut en résulter une amélioration de l’intégration.",
    motsCles: [
      "bâtiments existants",
      "non réglementaires",
      "zones à bâtir",
      "LCAT",
      "Lavaux",
      "agrandissement mineur",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art59_batiments_existants_hors_zones_batir",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 59",
    titreCourt:
      "Bâtiments existants non réglementaires b) hors des zones à bâtir",
    texte:
      "Les constructions existantes ne correspondant pas à la destination de la zone ne peuvent être transformées, agrandies ou reconstruites que dans les limites du droit fédéral et cantonal en la matière. Le permis de construire est dans tous les cas subordonné à l’autorisation préalable du Département des travaux publics.",
    motsCles: [
      "bâtiments existants",
      "hors zones à bâtir",
      "droit fédéral",
      "autorisation cantonale",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art60_surfaces_boisees",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 60",
    titreCourt: "Surfaces boisées",
    texte:
      "Dans toutes les zones, les parties boisées (forêts, rideaux d'arbres, haies, etc.) sont soumises à la loi forestière ou à la loi sur la protection de la nature, des monuments et des sites, ainsi qu'au règlement communal sur la protection des arbres. L’aire forestière est caractérisée par l'interdiction de déboiser et de bâtir à moins de 10 mètres de la lisière.",
    motsCles: [
      "surfaces boisées",
      "forêt",
      "lisière",
      "10 mètres",
      "protection des arbres",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art61_reserves_implantation_orientation",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 61",
    titreCourt: "Réserves d’implantation et d’orientation",
    texte:
      "Les constructions sont implantées sur l'alignement ou en retrait parallèlement à celui-ci. Pour des raisons d'orientation ou d'esthétique, la Municipalité peut autoriser, voire imposer une autre implantation.",
    motsCles: [
      "implantation",
      "orientation",
      "alignement",
      "esthétique",
      "municipalité",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art62_facades_non_paralleles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 62",
    titreCourt: "Façades non parallèles à la limite",
    texte:
      "La distance entre un bâtiment et la limite de propriété voisine est mesurée à partir du point le plus saillant de la construction comptant dans la surface bâtie. Lorsque la façade d'un bâtiment se présente obliquement par rapport à la limite de propriété, la distance réglementaire est mesurée à partir du milieu de la façade, perpendiculairement à la limite. À l'angle le plus rapproché de la limite, la distance réglementaire ne pourra pas être diminuée de plus d'un mètre.",
    motsCles: [
      "façade oblique",
      "distance aux limites",
      "point le plus saillant",
      "un mètre",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art63_changement_limites",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 63",
    titreCourt: "Changement des limites",
    texte:
      "Les changements de limites ou de niveaux de terrains, notamment en cas de fractionnement postérieur à la délivrance du permis de construire, ne peuvent avoir pour conséquence une violation des dispositions du présent règlement, notamment une réduction des distances aux limites ou entre bâtiments, une augmentation de la surface constructible, du nombre d'étages ou de la hauteur sur la corniche.",
    motsCles: [
      "changement de limites",
      "fractionnement",
      "distances",
      "surface constructible",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art64_constructions_souterraines",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 64",
    titreCourt: "Constructions souterraines",
    texte:
      "Sont souterraines, les constructions liées ou non à un bâtiment principal dont les deux tiers au moins du volume sont au-dessous du niveau du sol naturel, dont une face entière au plus reste visible après l’aménagement et dont la toiture est recouverte d'une couche de terre de 40 centimètres au minimum. Elles peuvent être construites dans les espaces réglementaires, mais à 3 mètres au moins de la limite de propriété, la Municipalité pouvant autoriser une distance inférieure dans des cas particuliers. Si elles sont contiguës au bâtiment principal, elles ne sont pas prises en considération pour l'application des règles relatives aux dimensions maximales des bâtiments. La Municipalité peut autoriser l'aménagement d'emplacements de stationnement sur la toiture des constructions souterraines si, par ailleurs, la création et le maintien de surfaces de verdure suffisantes sont garantis.",
    motsCles: [
      "constructions souterraines",
      "2/3 du volume",
      "3 mètres",
      "couche de terre",
      "stationnement",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art65_exceptions_distances",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 65",
    titreCourt: "Exceptions aux règles des distances",
    texte:
      "Moyennant entente entre voisins, la distance réglementaire entre bâtiments et limite de propriété peut être réduite sur l'un des biens-fonds à condition qu'il n'en résulte aucune diminution de la distance réglementaire entre les constructions présentes et futures sur chacune des propriétés intéressées. Tout accord intervenant entre voisins pour permettre cette réduction doit faire l'objet d'une servitude personnelle en faveur de la commune de Corsier-sur-Vevey. Cette servitude fixe la limite fictive nouvelle à partir de laquelle la distance entre bâtiment et limite de propriété devra être calculée pour toute construction envisagée sur le fonds servant.",
    motsCles: [
      "exception",
      "distance réglementaire",
      "servitude",
      "entente entre voisins",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art66_calcul_surface_batie",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 66",
    titreCourt: "Calcul de la surface bâtie",
    texte:
      "La surface bâtie est mesurée sur le plan du niveau de la plus grande surface. Pour les bâtiments à niveaux décalés, la surface à prendre en considération est celle donnée par la projection en plan de tous les niveaux. Les terrasses et terre-pleins non couverts et non excavés ne sont pas comptés dans la surface bâtie, de même que les seuils, perrons, terrasses, loggias et balcons d'une largeur maximum de 2 mètres, même fermés latéralement et couverts. Pour le calcul de la surface bâtie, il n'est pas tenu compte des constructions souterraines. Au surplus, l'art. 81 est réservé.",
    motsCles: [
      "surface bâtie",
      "projection en plan",
      "terrasses",
      "balcons",
      "constructions souterraines",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art67_maintien_surface_constructible",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 67",
    titreCourt: "Maintien de la surface constructible",
    texte:
      "En cas d'expropriation ou d'acquisition à l’amiable de terrains destinés à l'aménagement du domaine public, la Municipalité peut garantir aux propriétaires touchés que la surface expropriée ou cédée restera comprise dans le calcul de la surface constructible.",
    motsCles: [
      "surface constructible",
      "expropriation",
      "domaine public",
      "garantie",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art68_calcul_hauteur_facades",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 68",
    titreCourt: "Calcul de la hauteur des façades",
    texte:
      "La hauteur des façades est mesurée sur la corniche à partir de la cote moyenne du terrain naturel au droit de celles-ci. Si des corps de bâtiments sont décalés, la hauteur doit être respectée pour chaque élément de façade.",
    motsCles: [
      "hauteur des façades",
      "corniche",
      "terrain naturel",
      "corps de bâtiment",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art69_lucarnes",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 69",
    titreCourt: "Lucarnes",
    texte:
      "Les lucarnes doivent être placées en retrait ou à l’aplomb du parement extérieur du mur de façade, sans interruption de l'avant-toit. La Municipalité peut autoriser d’autres ouvertures en toiture. Les largeurs additionnées des lucarnes et autres ouvertures ne peuvent dépasser le tiers de la longueur de la façade si le toit est à quatre pans ou la moitié de la longueur de la façade si le toit est à deux pans. La hauteur des lucarnes sur la corniche sera au maximum de 1,80 mètre au-dessus de la couverture de la toiture du bâtiment, cote mesurée au droit de la face des lucarnes.",
    motsCles: ["lucarnes", "toiture", "avant-toit", "largeur", "hauteur"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art70_combles",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 70",
    titreCourt: "Combles",
    texte:
      "Lorsque les combles sont habitables, la hauteur minimale de 2,40 m sera respectée sur une surface de 3,5 m² au moins par pièce habitable. Une galerie aménagée dans un comble, accessible seulement par un escalier particulier et complétant l'appartement inférieur, ne sera pas comptée comme niveau supplémentaire. Dans ce cas, la surface de cette galerie ne peut excéder le tiers de la surface de l’appartement dont elle dépend.",
    motsCles: ["combles", "hauteur minimale", "galerie", "niveau supplémentaire"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art71_toitures_orientation_faites",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 71",
    titreCourt: "Toitures, orientation des faîtes",
    texte:
      "La Municipalité peut imposer l'orientation des faîtes, la pente des toitures, le genre de couverture, la largeur des avant-toits, notamment pour tenir compte du caractère de la zone et des bâtiments existants.",
    motsCles: [
      "orientation des faîtes",
      "pente de toiture",
      "genre de couverture",
      "avant-toits",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art72_pente_toitures",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 72",
    titreCourt: "Pente des toitures",
    texte:
      "La pente des toitures doit être comprise entre 30 % et 100 %. Dans la zone du village, elle sera au minimum de 65 %. Hors des zones industrielle et artisanale, seules les toitures à deux ou plusieurs pans sont admises ; l'art. 17 reste réservé. Pour les toits à deux pans, la surface du plus petit ne sera pas inférieure à la moitié de l'autre. Le faîte du toit est toujours plus haut que les corniches. La Municipalité peut autoriser les toits plats ou à un pan et à faible pente pour des cas particuliers, notamment des annexes de minime importance et pour les dépendances définies à l'art. 80. Les étages en attique sont interdits.",
    motsCles: [
      "pente des toitures",
      "30 %",
      "100 %",
      "zone du village",
      "toits à deux pans",
      "toits plats",
      "étages en attique",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art73_genre_couverture",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 73",
    titreCourt: "Genre de couverture",
    texte:
      "Les toitures seront recouvertes de tuiles en terre cuite ou en fibrociment ou béton, couleur tuile naturelle. Dans la zone du village, les tuiles plates du pays sont obligatoires. La Municipalité peut refuser un matériau ou une couleur qui nuirait à l’aspect des lieux.",
    motsCles: [
      "tuiles",
      "terre cuite",
      "fibrociment",
      "couleur tuile naturelle",
      "tuiles plates du pays",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art74_superstructures_antennes",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 74",
    titreCourt: "Superstructures, antennes",
    texte:
      "Tout élément émergeant de la toiture, notamment cheminées, cages d'escaliers, antennes radio ou télévision, est soumis à l'autorisation de la Municipalité. Celle-ci peut exiger l'installation d’antennes collectives de radio ou de télévision. Dans la mesure du possible, les antennes particulières seront dissimulées dans les combles.",
    motsCles: ["superstructures", "antennes", "autorisation", "cheminées"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art74bis_capteurs_solaires",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 74 bis",
    titreCourt: "Capteurs solaires",
    texte:
      "L'installation de capteurs solaires peut être autorisée, à condition de ne pas nuire à l'esthétique.",
    motsCles: ["capteurs solaires", "esthétique", "toiture"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art75_constructions_precaire",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 75",
    titreCourt: "Constructions à titre précaire",
    texte:
      "La Municipalité peut autoriser à titre précaire la construction de bâtiments de peu d'importance ou d'aménagements tels que places de stationnement, terrasses, etc., en anticipation sur les alignements de constructions, moyennant la signature d'une convention de précarité. Les travaux ainsi autorisés sont exécutés aux risques et périls des propriétaires. La Municipalité peut révoquer en tout temps l'autorisation délivrée, notamment lorsque la sécurité de la circulation se trouve menacée. En cas de révocation, le propriétaire ne peut prétendre à aucune indemnité et supporte les frais éventuels de démolition.",
    motsCles: [
      "constructions précaires",
      "convention de précarité",
      "anticipation",
      "alignements",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art76_anticipation_domaine_public",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 76",
    titreCourt: "Anticipation sur le domaine public",
    texte:
      "La Municipalité peut autoriser à titre précaire l'anticipation sur le domaine public de parties saillantes de bâtiments (avant-toits, corniches, balcons, marquises, etc.). Elle peut également autoriser à titre précaire la pose, dans le domaine public, de canalisations souterraines privées. Sur réquisition de la Municipalité, les bénéficiaires sont tenus en tout temps de démolir, déplacer ou modifier leurs installations lorsque les besoins du domaine public l’exigent. Ils supportent tous les frais de ces travaux sans pouvoir prétendre à indemnité. La Municipalité perçoit des taxes pour les anticipations et travaux autorisés sur le domaine public en vertu du présent règlement ; ces taxes font l'objet d'un tarif établi par la Municipalité et soumis à l'approbation du Conseil d'Etat.",
    motsCles: [
      "domaine public",
      "anticipation",
      "parties saillantes",
      "canalisations",
      "taxes",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art77_artisanat_commerce_zones_habitation",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 77",
    titreCourt: "Artisanat et commerce en zones d’habitation",
    texte:
      "L'artisanat et le commerce peuvent être autorisés dans les zones destinées à l'habitation pour autant qu'ils ne portent pas préjudice au voisinage (bruits, odeurs, fumées, dangers, etc.) et ne compromettent pas le caractère des lieux.",
    motsCles: [
      "artisanat",
      "commerce",
      "zones d’habitation",
      "nuisances",
      "caractère des lieux",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art78_chenils_dependances_fumiers",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 78",
    titreCourt: "Chenils, dépendances agricoles, fumiers",
    texte:
      "Les chenils à but lucratif, parcs avicoles et porcheries industrielles sont interdits sur le territoire de la commune. Dans les zones autres que la zone agricole, les porcheries, écuries, étables, abris pour le petit bétail, poulaillers, clapiers, ruchers et autres installations similaires sont interdits. Toutefois, la Municipalité peut accorder des dérogations pour de petites installations. Sur tout le territoire de la commune, les dépôts de fumier ou d’autres substances en décomposition doivent faire l'objet d'une autorisation de la Municipalité.",
    motsCles: [
      "chenils",
      "porcheries",
      "installations agricoles",
      "fumier",
      "décomposition",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art79_habitation_locaux_enterrer",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 79",
    titreCourt: "Habitation des locaux partiellement enterrés",
    texte:
      "L’habitation est interdite dans les sous-sols. N'est pas considéré comme tel le local dont une face au moins est complètement dégagée, pour autant que les règles d'habitabilité soient par ailleurs respectées.",
    motsCles: [
      "sous-sol",
      "locaux enterrés",
      "habitabilité",
      "locaux partiellement dégagés",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art80_dependances",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 80",
    titreCourt: "Dépendances",
    texte:
      "La construction de dépendances de 3 mètres de hauteur à la corniche et de 5 mètres au faîte au plus, à usage de garage pour deux voitures au maximum, buanderie, bûcher, etc., peut être autorisée dans les espaces réglementaires. Ces petites constructions ne peuvent en aucun cas servir à l'habitation ou au travail, sauf dans la zone du village où elles peuvent être utilisées dans le cadre de l'exercice d'une activité professionnelle.",
    motsCles: ["dépendances", "garage", "3 mètres", "5 mètres", "usage limité"],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art81_piscines",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 81",
    titreCourt: "Piscines",
    texte:
      "Les piscines non couvertes sont assimilées à des dépendances. Elles doivent toutefois être implantées à 3 mètres au moins de la limite de propriété. Elles n'entrent pas dans le calcul de la surface bâtie.",
    motsCles: [
      "piscines",
      "non couvertes",
      "dépendances",
      "3 mètres",
      "surface bâtie",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art82_acces_garages",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 82",
    titreCourt: "Accès aux garages",
    texte:
      "Les accès des garages et places de stationnement sur la voie publique ou privée ne doivent pas présenter des inconvénients ou un danger pour la circulation. La Municipalité peut imposer des aménagements particuliers.",
    motsCles: [
      "accès garage",
      "stationnement",
      "sécurité",
      "aménagements particuliers",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art83_roulottes_caravanes",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 83",
    titreCourt: "Roulottes, caravanes, etc.",
    texte:
      "L'entreposage à l'air libre, ainsi que l'utilisation de roulottes, caravanes et autres logements mobiles est interdit sur tout le territoire communal, sauf dans les terrains de camping aménagés pour ce genre d'installation. La Municipalité peut accorder des dérogations limitées dans le temps.",
    motsCles: [
      "roulottes",
      "caravanes",
      "logements mobiles",
      "camping",
      "dérogations",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art84_garages_places_stationnement",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 84",
    titreCourt: "Garages et places de stationnement",
    texte:
      "La Municipalité fixe le nombre de places privées de stationnement et de garages pour voitures qui doivent être aménagées par les propriétaires et à leurs frais, selon l'importance et la destination des nouvelles constructions, mais au minimum un garage ou une place de stationnement par logement ; ces emplacements seront en principe fixés en retrait des limites de construction. Ces dispositions sont également applicables lorsque la transformation ou le changement d'affectation d'un immeuble a pour effet d’augmenter les besoins en places de stationnement. Si l'exécution de ces garages ou places apparaît excessivement onéreuse ou inopportune, le propriétaire peut en être dispensé moyennant versement d'une contribution compensatoire de 4 000 francs par place manquante, payable lors de la délivrance du permis d'habiter. Ces contributions sont affectées à la construction de places de stationnement accessibles au public. Si des garages ou emplacements imposés sont supprimés ou utilisés à d'autres fins, le propriétaire doit les remplacer sur son fonds ou à proximité immédiate, ou verser la contribution compensatoire.",
    motsCles: [
      "garages",
      "places de stationnement",
      "contribution compensatoire",
      "4 000 francs",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_regles_art85_signalisation",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XV – Règles générales applicables à toutes les zones",
    article: "Art. 85",
    titreCourt: "Signalisation",
    texte:
      "Les propriétaires sont tenus, sans indemnité, de laisser apposer sur leur bâtiment ou sur la clôture de leur propriété les plaques indicatrices de nom de rue, de numérotation, de niveau d'hydrantes, de repères de canalisation, de signalisation routière, etc., ainsi que les horloges, conduites et appareils d'éclairage public et autres installations du même genre.",
    motsCles: ["signalisation", "plaques de rue", "numérotation", "éclairage public"],
    typeSource: "RGA",
  },

  // CHAPITRE XVI – Voies privées ou publiques
  {
    id: "corsier_voies_art86_voies_privees_definition",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVI – Voies privées ou publiques",
    article: "Art. 86",
    titreCourt: "Voies privées – définition",
    texte:
      "Constituent des voies privées soumises aux dispositions ci-après celles établies sur le domaine privé qui sont utilisées pour la circulation générale ou tendent à l'être.",
    motsCles: ["voies privées", "circulation générale", "domaine privé"],
    typeSource: "RGA",
  },
  {
    id: "corsier_voies_art87_construction_modification_suppression",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVI – Voies privées ou publiques",
    article: "Art. 87",
    titreCourt: "Constructions, modifications, suppressions",
    texte:
      "Aucune voie privée ne peut être établie, modifiée ou supprimée sans l'approbation de la Municipalité. Celle-ci peut exiger que les nouvelles voies privées soient établies suivant les normes adoptées pour la construction des voies publiques d'importance équivalente.",
    motsCles: [
      "voies privées",
      "établissement",
      "modification",
      "suppression",
      "normes",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_voies_art88_entretien",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVI – Voies privées ou publiques",
    article: "Art. 88",
    titreCourt: "Entretien des voies privées",
    texte:
      "Les voies privées doivent être régulièrement entretenues, nettoyées et praticables en tout temps ; ces travaux sont à la charge des propriétaires des bâtiments bordiers.",
    motsCles: ["entretien", "voies privées", "propriétaires bordiers"],
    typeSource: "RGA",
  },
  {
    id: "corsier_voies_art89_entrees_vehicules",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVI – Voies privées ou publiques",
    article: "Art. 89",
    titreCourt: "Entrées de véhicules",
    texte:
      "Tout propriétaire qui possède une entrée pour véhicules est tenu de la raccorder à la chaussée selon les prescriptions de la Municipalité et d'en assurer l'entretien.",
    motsCles: ["entrées véhicules", "chaussée", "entretien"],
    typeSource: "RGA",
  },
  {
    id: "corsier_voies_art90_murs_clotures_haies",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVI – Voies privées ou publiques",
    article: "Art. 90",
    titreCourt: "Murs, clôtures et haies bordant les voies",
    texte:
      "Les murs, clôtures et haies bordant les voies privées ou publiques doivent être autorisés par la Municipalité, qui fixe dans chaque cas, d'entente avec le propriétaire, leur implantation et leurs dimensions. Les dispositions de la loi sur les routes et son règlement d'application sont réservées.",
    motsCles: ["murs", "clôtures", "haies", "voies", "autorisation"],
    typeSource: "RGA",
  },
  {
    id: "corsier_voies_art91_travaux_domaine_public",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVI – Voies privées ou publiques",
    article: "Art. 91",
    titreCourt: "Travaux sur le domaine public",
    texte:
      "Tout travail à exécuter sur le domaine public (fouilles, échafaudages, dépôts, etc.) doit faire l'objet d'une autorisation délivrée par la Municipalité.",
    motsCles: ["domaine public", "travaux", "autorisation"],
    typeSource: "RGA",
  },

  // CHAPITRE XVII – Police des constructions
  {
    id: "corsier_police_art92_enquete_publique_dossier",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVII – Police des constructions",
    article: "Art. 92",
    titreCourt: "Enquête publique, présentation du dossier",
    texte:
      "Le dossier d’enquête comprend obligatoirement, outre les pièces énumérées par la loi sur les constructions et l'aménagement du territoire et par son règlement d’application : a) sur le plan de situation établi par le géomètre, le relevé coté de toutes les surfaces bâties existantes cadastrées ou non sur la parcelle concernée, y compris les dépendances, le tracé des canalisations projetées y compris leurs raccordements sur les collecteurs existants, le niveau de référence et les cotes d'altitude du terrain naturel aux angles des nouvelles constructions, ainsi que le report des accès, les places de stationnement et les murs importants ; b) les profils du terrain naturel relevés par le géomètre dans l'axe des constructions ainsi que sur toutes les façades, profils rattachés altimétriquement au niveau de référence ; les profils du terrain aménagé sur toutes les façades, y compris leurs raccordements au terrain naturel ; d) un projet (plans et coupes) des aménagements extérieurs comprenant les accès, talus et terrasses, les places de stationnement pour véhicules, les espaces verts, les murs, clôtures, plantations, haies, etc. ; e) un état descriptif des matériaux et des teintes des façades, balcons, volets, clôtures, etc. ; f) pour la zone du village, l'art. 10 est applicable. La Municipalité peut, lorsque la nature du projet le justifie, dispenser le constructeur de la présentation de certaines pièces.",
    motsCles: [
      "dossier d’enquête",
      "plans",
      "profils de terrain",
      "aménagements extérieurs",
      "matériaux",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_police_art93_dossier_complementaire",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVII – Police des constructions",
    article: "Art. 93",
    titreCourt: "Dossier complémentaire",
    texte:
      "Le constructeur est tenu de produire à la Municipalité, au plus tard lors de la demande du permis d'habiter, un relevé coté à l'échelle du plan cadastral du tracé exact des canalisations d'eaux claires et d'eaux usées (situation, profondeur au radier, diamètre et pente) et de toutes les installations d'épuration (séparateur, désableur, etc.). Il doit également remettre, dans le même délai, une déclaration d'un ingénieur reconnu attestant que les ouvrages de protection civile ont été exécutés conformément aux normes en vigueur.",
    motsCles: [
      "dossier complémentaire",
      "canalisations",
      "eaux claires",
      "eaux usées",
      "protection civile",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_police_art94_gabarits",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVII – Police des constructions",
    article: "Art. 94",
    titreCourt: "Gabarits",
    texte:
      "La Municipalité peut exiger la pose de gabarits, la production de photomontages, de maquettes et d'un échantillonnage des couleurs et matériaux de la construction projetée, aux frais du constructeur et sous sa responsabilité.",
    motsCles: ["gabarits", "photomontages", "maquettes", "couleurs", "matériaux"],
    typeSource: "RGA",
  },
  {
    id: "corsier_police_art95_taxes",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVII – Police des constructions",
    article: "Art. 95",
    titreCourt: "Taxes",
    texte:
      "Les taxes pour les permis de construire, permis d'habiter, d'occuper ou d'utiliser, et autres, font l'objet de tarifs spéciaux établis par la Municipalité, soumis à l'adoption du Conseil communal et à l'approbation du Conseil d'Etat.",
    motsCles: ["taxes", "permis de construire", "permis d'habiter", "tarifs"],
    typeSource: "RGA",
  },
  {
    id: "corsier_police_art96_edifices_publics",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVII – Police des constructions",
    article: "Art. 96",
    titreCourt: "Édifices publics",
    texte:
      "La Municipalité peut autoriser des dérogations aux prescriptions du présent règlement pour permettre l'édification de bâtiments ou ouvrages d'intérêt public ou indispensables à un service public qui, par leur destination ou leur nature, exigent des dispositions particulières.",
    motsCles: [
      "édifices publics",
      "intérêt public",
      "service public",
      "dérogations",
    ],
    typeSource: "RGA",
  },
  {
    id: "corsier_police_art97_secteur_s_protection_eaux",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVII – Police des constructions",
    article: "Art. 97",
    titreCourt: "Secteur « S » de protection des eaux",
    texte:
      "À l'intérieur des secteurs « S » de protection des eaux figurant sur le plan, les dispositions des lois fédérales et cantonales sur la protection des eaux sont réservées. Tous travaux pouvant toucher directement ou indirectement un secteur « S » de protection des eaux seront soumis à l'Office cantonal de la protection des eaux.",
    motsCles: [
      "secteur S",
      "protection des eaux",
      "office cantonal",
      "travaux soumis",
    ],
    typeSource: "RGA",
  },

  // CHAPITRE XVIII – Dispositions finales
  {
    id: "corsier_final_art98_lcat_rcat",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVIII – Dispositions finales",
    article: "Art. 98",
    titreCourt: "LCAT, RCAT",
    texte:
      "Pour tout ce qui ne figure pas dans le présent règlement, la loi sur les constructions et l'aménagement du territoire et son règlement d'application, ainsi que la loi sur le plan de protection de Lavaux, sont applicables.",
    motsCles: ["LCAT", "RCAT", "Lavaux", "droit cantonal"],
    typeSource: "RGA",
  },
  {
    id: "corsier_final_art99_abrogations",
    commune: "Corsier-sur-Vevey",
    source: SOURCE_CORSIER,
    chapitre: "CHAPITRE XVIII – Dispositions finales",
    article: "Art. 99",
    titreCourt: "Abrogations et adoption du règlement",
    texte:
      "Le présent règlement abroge, dès son entrée en vigueur, le règlement approuvé par le Conseil d'Etat le 15 mars 1963, ainsi que les modifications des 29 mars 1968, 10 novembre 1972 et 30 juillet 1975, ainsi que le plan d'extension partiel « Le Mur Blanc – LB Banderette » approuvé par le Conseil d'Etat le 18 juillet 1969. Il a été adopté par la Municipalité de Corsier-sur-Vevey dans sa séance du 1er juin 1982 et soumis à l'enquête publique du 11 juin 1982 au 12 juillet 1982. Il a été adopté par le Conseil communal dans sa séance du 23 février 1983, puis approuvé par le Conseil d'Etat du Canton de Vaud dans sa séance du 3 avril 1985.",
    motsCles: [
      "abrogation",
      "ancien règlement",
      "adoption",
      "enquête publique",
      "Conseil d'Etat",
    ],
    typeSource: "RGA",
  }

];
